ccflags-y := -Ofast -ffast-math -fgcse-lm -fgcse-sm -fsched-spec-load -fforce-addr -fsingle-precision-constant -mtune=cortex-a9 -marm -march=armv7-a -mfpu=neon -ftree-vectorize -mvectorize-with-neon-double

obj-$(CONFIG_MACH_PYRAMID) += pyramid-panel.o
obj-$(CONFIG_MACH_SHOOTER) += shooter-panel.o
obj-$(CONFIG_MACH_SHOOTER_U) += shooter_u-panel.o
obj-$(CONFIG_MACH_SHOOTER_K) += shooter_k-panel.o
obj-$(CONFIG_MACH_SHOOTER_CT) += shooter_ct-panel.o
obj-$(CONFIG_MACH_RIDER) += rider-panel.o
obj-$(CONFIG_MACH_VILLEC2) += villec2-panel.o
obj-$(CONFIG_MACH_HOLIDAY) += holiday-panel.o
obj-$(CONFIG_MACH_VIGOR) += vigor-panel.o
obj-$(CONFIG_MACH_RUBY) += ruby-panel.o
